# _config.yml

collections:
  posts_es:
    output: true
    permalink: /es/blog/:title/
  posts_en:
    output: true
    permalink: /en/blog/:title/

defaults:
  - scope:
      path: ""
      type: "posts_es"
    values:
      lang: "es"
  - scope:
      path: ""
      type: "posts_en"
    values:
      lang: "en"
      
