# _config.yml

theme: jekyll-theme-minimal
title: Joaquín del Cerro | Arquitecto de Software
description: Un espacio para mis artículos, proyectos e investigación sobre arquitectura de software, GIS e Inteligencia Artificial.
