# _config.yml

collections:
  posts_es:
    output: true
    permalink: /es/blog/:title/
  posts_en:
    output: true
    permalink: /en/blog/:title/

defaults:
  - scope:
      path: ""
      type: "posts_es"
    values:
      lang: "es"
  - scope:
      path: ""
      type: "posts_en"
    values:
      lang: "en"
      
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
  
lang: es-ES
